apiVersion: v1
kind: Service
metadata:
  name: tikv-cluster-pd-external
  namespace: tikv
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: tidb-cluster
    app.kubernetes.io/instance: tikv-cluster
    app.kubernetes.io/component: pd
  ports:
  - name: client
    port: 2379
    targetPort: 2379
